### PR TITLE
Feature/jacob ayu/1209383246 calendar banner formatting

### PR DESCRIPTION
**Pull request by deepanshasingh**
### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Toggle between calendar and list pages
### Testing
How did you confirm your changes worked? 
Toggle changes pages

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by justinyaodu — APPROVED** [review]
LGTM!

**Review by eliasfang — APPROVED** [review]
Same note as with the last PR. It'd be helpful if you attached pics of it working but I trust that it does. Nice work!

**Comment by dmhacker** [comment]
Working on Chrome:

image

Working on Firefox:

image

Should work on all browsers, since I added Luxon to handle date parsing for the `scheduled_time` field, which was in a bit of a weird format.

**Comment by dmhacker** [comment]
I should add that a more consistent fix would be to convert the `scheduled_time` to an ISO string in order to keep it inline with every other date format; I believe Justin already mentioned this in Slack. Particularly, I worried that timezones could get a bit messy because they're currently not tracked in `scheduled_time` unlike in ISO strings. It's really up to the user's browser to interpret the time zones as is, so this really only works when the user is in the same timezone as the backend server.

I'm going to keep this PR open until this is resolved. @justinyaodu @TritonSE/og-yoga-devs

**Comment by dmhacker** [comment]
After some more investigating, it seems that the original ISO string was being replaced by a prettified version of the date upon deserialization. To keep backwards compatibility, I've added a separate field `iso_scheduled_time` that has the date in ISO string format. This means that Luxon can actually be removed, since everything is now in ISO format. I've also removed the unused _add event_ button.

Looks like we're done here; I'll merge this into `main`.

**Pull request merged**
