### PR TITLE
Feature/thomas liardjava/998196844 create readme

### PR DESCRIPTION
**Pull request by mingkaili**
### Administrative Info
Monday Board ID: 998196844

### Changes
What changes did you make?
- Added readme.md for documentation

### Testing
How did you confirm your changes worked? 
- Pic on github

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
Screen Shot 2021-01-25 at 6 42 23 PM

### CODE REVIEW

**Review by shravan1k — APPROVED** [review]
LGTM

**Comment by shravan1k** [comment]
This isn't related to the code, but on the topic of documentation I think we need to also have a one-line subtitle.

**Comment by mingkaili** [comment]
@shravan1k Want to write the one line subtitle? Just commit and push directly to this branch.

**Review by eliasfang — APPROVED** [review]
LGTM! Question: should the node.js, javascript, and aws images on the README link to anywhere?

**Pull request merged**
